server.port: 9913

security:
  ignored: /v2/api-docs

spring.oauth2.resource:
  id: cloud_controller
  jwt:
    keyUri: ${sso.tokenKey}

services:
  store:
    serverName: ${mongo.host:localhost}
    serverPort: ${mongo.port:27017}
    dbName: ${mongo.dbname:models}
    user: ${mongo.username:}
    password: ${mongo.password:}
