server.port: 9913

security:
  ignored: /v2/api-docs,/healthz

spring.oauth2.resource:
  id: tap
  jwt:
    keyUri: ${sso.tokenKey}

services:
  store:
    serverName: ${mongo.host:localhost}
    serverPort: ${mongo.port:27017}
    dbName: ${mongo.dbname:models}
    user: ${mongo.username:}
    password: ${mongo.password:}

storage:
  local:
    basePath: /data/artifacts

multipart:
  maxFileSize: 2048Mb
  maxRequestSize: 2048Mb

spring.profiles.active: default,local

logging:
  level:
    org.trustedanalytics: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
