server.port: 9913

security:
  ignored: /v2/api-docs

spring.oauth2.resource:
  id: cloud_controller
  jwt:
    keyUri: ${vcap.services.sso.credentials.tokenKey}

services:
  store:
    serverName: ${vcap.services.models-store.credentials.hostname:localhost}
    serverPort: ${vcap.services.models-store.credentials.port:27017}
    dbName: ${vcap.services.models-store.credentials.dbname:models}
    user: ${vcap.services.models-store.credentials.username:}
    password: ${vcap.services.models-store.credentials.password:}
